repository: "tokoik/tokoik.github.io"
github_username: tokoik
lsi: false
safe: true
source: posts
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
